---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - picocom
    state: present

- name: Add users to dialout and video
  become: true
  ansible.builtin.user:
    name: "{{ main_user_name }}"
    groups: dialout,video
    append: yes
