- name: ARM64 Download SDK
  ansible.builtin.get_url:
    url: https://dl.orbbec3d.com/dist/astra/v2.1.3/AstraSDK-v2.1.3-Linux-arm.zip
    dest: /home/{{ main_user_name }}/ansible-files/AstraSDK.zip
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"
    mode: "0644"
    checksum: "sha512:67b7a5430a95ff779e1b548bc6babb72da938b7cd20078d875cdd2bdfe6907b90457f5b7f46e6f26c46423b73bf07da3891591562b403be429bca65f3a1f69df"

- name: ARM64 Unarchive SDK
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/{{ main_user_name }}/ansible-files/AstraSDK.zip
    dest: /home/{{ main_user_name }}/ansible-files/
    include:
      - AstraSDK-v2.1.3-94bca0f52e-20210611T023312Z-Linux-aarch64.tar.gz
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"

- name: ARM64 Unarchive Linux version
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/{{ main_user_name }}/ansible-files/AstraSDK-v2.1.3-94bca0f52e-20210611T023312Z-Linux-aarch64.tar.gz
    dest: /home/{{ main_user_name }}/ansible-files/
    owner: "{{ main_user_name }}"
    group: "{{ main_user_name }}"

- name: ARM64 Copy to install directory
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /home/{{ main_user_name }}/ansible-files/AstraSDK-v2.1.3-94bca0f52e-20210611T023312Z-Linux-aarch64/{{ item }}/
    dest: /opt/AstraSDK/{{ item }}/
    mode: "0755"
    owner: root
    group: root
  loop:
    - include
    - lib
