---
- name: Install docker dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get architecture
  ansible.builtin.command: dpkg --print-architecture
  register: architecture
  changed_when: false

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker packages
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      # - uidmap # rootless only
    state: present

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ main_user_name }}"
    groups: docker
    append: yes
